server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/booksystem?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapping/*mapper.xml
  type-aliases-package: com.example.entity

#showSql
#logging:
#  level:
#    com:
#      example:
#        mapper : debug
